### ISSUE TITLE
Handling errors differently

### ISSUE THREAD

**Issue by michaeldauria** [promiscuous-io/promiscuous#16]
Instead of complaining and stopping the processing of messages, how about failed messages are moved to another queue for later processing? This would allow for properly formatted messages to go through as if nothing was wrong. A positive side affect of this is that one could set up some sort of alert  based on the number of messages in the failed queue (it should always be at 0) as well.

**Comment by nviennot** [comment]
Sadly that's unsafe, because of data dependencies.
