### ISSUE TITLE
destroy / destroy_all don't work

### ISSUE THREAD

**Issue by nik** [promiscuous-io/promiscuous#25]
Seems that I can't destroy anything, just returns false.

**Comment by nik** [comment]
Specifically, (as of right now) on Actions. I can destroy members, but if I try
`Action::Base.all.destroy_all` , the count is returned, however they're all still there

**Comment by nviennot** [comment]
Will investigate.

**Comment by nviennot** [comment]
This is not a promiscuous bug. BrandActions have this callback:

``` ruby
before_destroy :ensure_action_can_be_destroyed
def ensure_action_can_be_destroyed
  self.state == "created"
end
```

**Comment by nviennot** [comment]
FYI, You can use `delete` instead to bypass callbacks.

**Comment by nik** [comment]
ah. thanks
