### ISSUE TITLE
Bidirectional pubsub

### ISSUE THREAD

**Issue by psugihara** [promiscuous-io/promiscuous#27]
Say I want to have bidirectional pubsub nodes. That is, Node A makes User models that Node B subscribes to and Node B creates Order models that Node A subscribes to.

Is this possible?

The tutorial states:
"You should start the subscriber first, otherwise the appropriate queues will not be created."

**Comment by nviennot** [comment]
To make the system easier to understand, we decided not to support that feature.
It gets funny when one decides to do a delete while the other one wants to do an update

**Comment by nviennot** [comment]
Actually, you can use ephemerals to send data back to the publisher.

**Comment by psugihara** [comment]
> > It gets funny when one decides to do a delete while the other one wants to do an update

Wouldn't this only be an issue if you're publishing and subscribing to the same model?
It just seems unlikely that you'll have acyclic dependencies in most SOA's.

**Comment by nviennot** [comment]
I didn't read your question properly. Sorry about that.

Yes, Promiscuous supports the scenario you are describing. Essentially, you need to start all the subscriber workers first, because their queues get created once they connect.
