### ISSUE TITLE
Micro Services Architecture

### ISSUE THREAD

**Issue by andyl** [promiscuous-io/promiscuous#42]
This video describes a micro-services architecture which seems similar to promiscuous.  He uses Kafka instead of RabbitMQ as the persistent data bus.  I hope you find the video interesting. 

http://oredev.org/2013/wed-fri-conference/implementing-micro-service-architectures

**Comment by kareemk** [comment]
Thanks for sharing @andyl. This is indeed very interesting and philosophically there is a lot of overlap: especially the idea of encapsulation at the data layer.
