### ISSUE TITLE
Can't enable in max_prepared_transactions in Heroku

### ISSUE THREAD

**Issue by gabrieljoelc** [promiscuous-io/promiscuous#46]
I have an existing application that is using ActiveRecord with PostgreSQL, which currently I need the max_prepared_transactions for. Here's what the Heroku ticket response said when I made a request to enable it:

> No, unfortunately, we have no plans to support max_prepared_transactions at this time. The reasons behind this are outlined in this post right here: http://www.postgresql.org/message-id/7105.1240422511@sss.pgh.pa.us

**Comment by kareemk** [comment]
Implemented on master.

Note that currently you'll have to add a '_v' timestamp field to all published models and add the _promiscuous table. See https://github.com/promiscuous-io/promiscuous/blob/master/spec/spec_helper/active_record.rb#L50-L53.

I'll have helpers and/or generators soon to make this easy.
