### ISSUE TITLE
How do you handle changes to models?

### ISSUE THREAD

**Issue by nathanpalmer** [promiscuous-io/promiscuous#53]
I'm not a user of the project (yet) and just watched the 2013 RubyConf video introduction. What I'm curious about is as things change in your application it's guaranteed that at some point a field is named a model is renamed, new models introduced, etc. Using a system like promiscuous seems interesting but I'm curious how it handles these situations. 
- Model is renamed - Overriding class names - https://github.com/promiscuous-io/promiscuous/wiki/Features-and-Recipes#overriding-class-names
- Field is renamed - ?
- New models introduced - Initial sync - https://github.com/promiscuous-io/promiscuous/wiki/Going-to-Production#initial-sync

From what I can tell there is an answer for everything here except for a field getting renamed. Ideally we wouldn't have to rename all the subscribers in a case like this and could simply alias on the publisher side.

**Comment by kareemk** [comment]
You can do exactly that.  e.g.

Before:

``` ruby
class User
  publish do
    field :name
  end
end
```

After:

``` ruby
class User
  publish do
    field :new_name
  end
  publish :name

  def name
    self.new_name
  end
end
```

They key feature here is that you can publish _any_ method on the model making situations like this one easy to deal with.
