### ISSUE TITLE
Delete not working, but publish is

### ISSUE THREAD

**Issue by AdamKyle** [promiscuous-io/promiscuous#54]
Publishing records works fine. How ever when you publish the deletion of a record from the publisher to the subscriber, eg:

```
  [1m[35m (0.1ms)[0m  BEGIN
  [1m[36m (0.1ms)[0m  [1mCOMMIT[0m
[promiscuous] [receive] {"operations":[{"types":["ApiKey"],"id":"3","operation":"destroy"}],"app":"aisis_platform","current_user_id":1,"timestamp":1399565098780,"generation":1,"host":"blackline","dependencies":{"write":["219954:2"]}}
```

In this case, the publisher is telling the subscriber to delete the api key on id 3, this never happens. The API key is still present in the subscriber table. How evr if I create a new api key in the publisher

```
  [1m[35m (0.1ms)[0m  BEGIN
  [1m[36mSQL (0.2ms)[0m  [1mINSERT INTO "api_keys" ("_v", "api_key", "id", "xaaron_users_id") VALUES ($1, $2, $3, $4) RETURNING "id"[0m  [["_v", 1125899906842625], ["api_key", "cfc09d2daa2a6c1629d9bf5d2e401725"], ["id", 4], ["xaaron_users_id", 1]]
  [1m[35m (2.4ms)[0m  COMMIT
[promiscuous] [receive] {"operations":[{"types":["ApiKey"],"id":"4","attributes":{"xaaron_users_id":1,"api_key":"cfc09d2daa2a6c1629d9bf5d2e401725"},"operation":"create"}],"app":"aisis_platform","current_user_id":1,"timestamp":1399565287267,"generation":1,"host":"blackline","dependencies":{"write":["217939:1"]}}
```

You can see that the subscriber listens, receives, and inserts the new api key - now the subscriber has two API Keys, when it should have one.

**Comment by kareemk** [comment]
Deletes are postponed on the subscriber to prevent the race where an destroy is processed before an update resulting in the record being deleted then upserted.

The current default is to postpone deletes by an hour. This value can easily be changed through configuration (see https://github.com/promiscuous-io/promiscuous/blob/master/lib/promiscuous/config.rb#L64). I wouldn't recommend setting this any shorter then 1 minute (note that you'll need to make sure to change the destroy_check_interval to be shorter then the destroy_timeout).

**Comment by kareemk** [comment]
After further review I realize that the delete should be processed twice, once when it is received and then another time postponed. This will for most cases when there isn't a race process the delete instantaneously but also catch races when they occur.

I'll get a fix in soon.

**Comment by AdamKyle** [comment]
Ok thank you for the clarification. Would setting the value to 15 seconds cause any issues you could see?

**Comment by kareemk** [comment]
You _could_ have a race within that timeframe if an update takes a long time (15s+) and a delete sneaks in and is processed first. But if this is in a development environment then there should be no problem doing this.

That said, I should have a fix out within the hour.
