### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by MattRogish** [promiscuous-io/promiscuous#59]
Hi,

The docs state it requires PostgreSQL - any idea what would need to change in order to support MySQL? What's Postgres-specific? Thanks!

**Comment by kareemk** [comment]
Support for the "RETURNING" clause in update and insert (see RETURNING in http://www.postgresql.org/docs/9.1/static/sql-update.html).

Note that it is possible to support MySQL without it -- its just a bunch of work and not ideal as row-level locks would need to be taken on every update/insert.

**Comment by kareemk** [comment]
@MattRogish i'm curious what usecase you're currently/exploring using promiscuous for?

**Comment by MattRogish** [comment]
Hi Kareem,

Thanks for the note. Basically, taking a monolithic Rails app and breaking it up into smaller chunks, then some sort of pubsub across apps/servers. Most of the Ruby/Rails stuff for pubsub that I can find is either roll-your-own, or only works for a single server. 

If I was Facebook (let's assume this use-case makes sense, because it kind of maps to an application I'm interested in) when a user "likes" a post, I'd publish that 'like' AR object (which contains a post ID and a like ID or something) and then have a bunch of other services listen to that (an email notifier, a dashboard which shows all the likes across the system, a list of liked posts in the last hour, all your posts that have been liked, all your liked posts, etc.).

In this case, the pub DBMS happens to be MySQL.

Thanks,

## 

Matt

**Comment by kareemk** [comment]
That's the ideal usecase for this project -- we took a monolithic rails app and with promiscuous migrated it to a micro-services architecture with 12 (and fast growing) services. 

I'll work on MySQL support this weekend and hopefully have something for you soon.

**Comment by kareemk** [comment]
Closed by https://github.com/promiscuous-io/promiscuous/commit/afe361d403b95842e6b8163776110e944806b5a5

**Comment by kareemk** [comment]
Released version [1.0.0.beta5](https://rubygems.org/gems/promiscuous/versions/1.0.0.beta5)

**Comment by MattRogish** [comment]
Awesome!!! thanks Kareem!!! you're amazing :+1:
