### ISSUE TITLE
Rails 4.x Support

### ISSUE THREAD

**Issue by diegodurs** [promiscuous-io/promiscuous#63]
Do you know the possible issues related to Rails 4.0 support? What has to be done?
Anyone else would like this?

**Comment by kareemk** [comment]
4.x is supported. Have you had issues?

**Comment by diegodurs** [comment]
I haven't try it yet.
I guess the roadmap must be updated then:
https://github.com/promiscuous-io/promiscuous/wiki/miscellaneous#roadmap

**Comment by kareemk** [comment]
Ah. Updated that. Thanks.
