### ISSUE TITLE
Inconsistent Sync

### ISSUE THREAD

**Issue by perkins2099** [promiscuous-io/promiscuous#64]
Ruby 2.1.2
Rails 4.1.4
Promiscuous 1.0.0.beta5

Syncing messages through a rabbitmq server on EC2, clustered through a load balancer.  Almost never receive all of the data that is published and having a hard time tracking down the problem.

I ran a test locally using the load balancer and rabbitMQ servers.  Ran faster and flawlessly.

Are there tools to help trackdown if a message originates at the publisher and where it ends up?  Any other recommendations?

**Comment by kareemk** [comment]
Could you please share more details on the setup your running on EC2? Perhaps screenshots of your rabbit config.

To track the messages set the logging level to DEBUG in the promiscuous initializer on both the publisher and the subscriber and you should see where things are breaking down.

Also, are you running the publisher recover worker (via: `promiscuous publisher_recover`)?

Are you running ActiveRecord or Mongoid?

**Comment by perkins2099** [comment]
Thanks Kareem!

ActiveRecord - Postgres

Not running promiscuous publisher_recover - didn't see it in the dox.  Didn't see any exceptions coming through in my promiscuous error logging stuff below:
  # All the settings are optional, the given values are the defaults.

``` ruby
Promiscuous.configure do |config|
  # All the settings are optional, the given values are the defaults.
  config.app            = 'Uapp'
  config.amqp_url       = ENV['rabbit_url']
  config.redis_url      = 'redis://localhost/'
  #config.backend        = :rubyamqp
  config.logger         = Rails.logger
  config.error_notifier = proc do |exception|
    Rails.logger.fatal "Choked on #{exception.payload}"
    NewRelic::Agent.notice_error(exception)
  end
```

Wasn't sure how to set the promiscuous logging level.

EC Rabbits:
T2.micro instances
Load Balancer

I can't seem to find the rabbitmq.config file or anything.  For the config.. would something like ..rabbitmqctl environment or rabbitmqctl cluster_status be helpful?

Thanks!

**Comment by kareemk** [comment]
``` ruby
config.logger.level = Logger::DEBUG
```

To start a screenshot of the overview page of the rabbitmq admin panel should be fine.

I'll update the docs to be more explicit about the publisher_recovery worker. With it running are you still seeing the data loss issue?

If you're still struggling I'm happy to setup some time to remote pair and try and figure this out.

**Comment by perkins2099** [comment]
![rabbitmq management](https://cloud.githubusercontent.com/assets/1720524/4836922/5bb5e9ca-5fcc-11e4-878b-de8747ebc8d3.png)

I'm still seeing pretty inconsistent sync.  I have 5000 records and only 1300 came through on this last try with the recovery bit running.

I'm syncing by being in console on the publisher and doing..

Link.all.find_each { |u| u.promiscuous.sync }

Id enjoy a few minutes of your time whenever it is possible.  Thanks so much.

**Comment by kareemk** [comment]
Please reopen if this is still an issue.
